<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.api_platform.json_schema.json_schema_generate_command' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/JsonSchema/Command/JsonSchemaGenerateCommand.php';

return $this->services['console.command.public_alias.api_platform.json_schema.json_schema_generate_command'] = new \ApiPlatform\Core\JsonSchema\Command\JsonSchemaGenerateCommand(($this->privates['api_platform.hydra.json_schema.schema_factory'] ?? $this->getApiPlatform_Hydra_JsonSchema_SchemaFactoryService()), $this->parameters['api_platform.formats']);
