<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQnULPxr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQnULPxr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQnULPxr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQnULPxr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQnULPxr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QnULPxr',
    'container.build_id' => '1404af59',
    'container.build_time' => 1571991591,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQnULPxr');
